### ISSUE TITLE
Add possibility to configure a new root CA 

### ISSUE THREAD

**Issue by antarus** [CybercentreCanada/assemblyline-core#390]
Hello, Could it be possible to add the possibility of adding our root CA  in assemblyline-core for access our registry or other service

**assemblyline version**: 4.1.stable
**kubectl version**:
`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}`
**kubernetes version**:
`Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}`

if I add my Root certificate in service's dockerfile, i can update different service in TLS.
For example, in yara's dockerfile, after i add my CA in /usr/local/share/ca-certificates, the yara service can update without having to specify `ssl_ignore_errors: true` in `service_manifest.yml`. These updates are done on a git repository in my infrastructure.

However by doing the same thing in assemblyline-core, the updater (urlib3? ) does not seem to take into account the certificates installed in the docker.

<details>
  <summary>Updater logs</summary>
  
{"@timestamp": "2021-12-10 09:23:24,515", "event": { "module": "assemblyline", "dataset": "assemblyline.service.updater" }, "host": { "ip": "10.233.116.178", "hostname": "updater-6d6d4fcb97-c2hqc" }, "log": { "level": "INFO", "logger": "assemblyline.service.updater" }, "process": { "pid": "1" }, "message": "Started"}
{"@timestamp": "2021-12-10 09:23:24,788", "event": { "module": "assemblyline", "dataset": "assemblyline.service.updater" }, "host": { "ip": "10.233.116.178", "hostname": "updater-6d6d4fcb97-c2hqc" }, "log": { "level": "ERROR", "logger": "assemblyline.service.updater" }, "process": { "pid": "1" }, "message": "Exiting:\nTraceback (most recent call last):\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 699, in urlopen\n    httplib_response = self._make_request(\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 382, in _make_request\n    self._validate_conn(conn)\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 1010, in _validate_conn\n    conn.connect()\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/urllib3/connection.py\", line 416, in connect\n    self.sock = ssl_wrap_socket(\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py\", line 449, in ssl_wrap_socket\n    ssl_sock = _ssl_wrap_socket_impl(\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py\", line 493, in _ssl_wrap_socket_impl\n    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)\n  File \"/usr/local/lib/python3.9/ssl.py\", line 500, in wrap_socket\n    return self.sslsocket_class._create(\n  File \"/usr/local/lib/python3.9/ssl.py\", line 1040, in _create\n    self.do_handshake()\n  File \"/usr/local/lib/python3.9/ssl.py\", line 1309, in do_handshake\n    self._sslobj.do_handshake()\nssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/requests/adapters.py\", line 439, in send\n    resp = conn.urlopen(\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 755, in urlopen\n    retries = retries.increment(\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/urllib3/util/retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='registry.hub.docker.com', port=443): Max retries exceeded with url: /v2/repositories/cccs/assemblyline-service-apkaye/tags?page_size=5&page=1&name=stable (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_core/server_base.py\", line 99, in run\n    self.try_run()\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_core/updater/run_updater.py\", line 478, in try_run\n    self.container_versions()\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_core/updater/run_updater.py\", line 464, in container_versions\n    image_name, tag_name, auth = get_latest_tag_for_service(service, self.config, self.log)\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_core/updater/helper.py\", line 127, in get_latest_tag_for_service\n    tags = _get_dockerhub_tags(image_name, update_channel)\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_core/updater/helper.py\", line 169, in _get_dockerhub_tags\n    resp = requests.get(url)\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/requests/api.py\", line 75, in get\n    return request('get', url, params=params, **kwargs)\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/requests/api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/requests/sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/requests/sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/requests/adapters.py\", line 514, in send\n    raise SSLError(e, request=request)\nrequests.exceptions.SSLError: HTTPSConnectionPool(host='registry.hub.docker.com', port=443): Max retries exceeded with url: /v2/repositories/cccs/assemblyline-service-apkaye/tags?page_size=5&page=1&name=stable (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))\n"}
</details>
the `registry.hub.docker.com` is a registry in our environment

**Comment by cccs-rs** [comment]
There's two ways to go about this:

There's a configuration in values.yaml:  `configuration.services.allow_insecure_registry: true`

or you can create a configmap containing your CA bundle and mount that configmap using coreVolumes & coreMounts.
This will involve adding `REQUESTS_CA_BUNDLE` to coreEnv to point to your bundle of external certificates for the system to use should `configuration.services.allow_insecure_registry` not be set.

**Comment by antarus** [comment]
Hello, I have updated the core image with my certificates and added the environment variable pointing to /etc/ssl/certs/ca-certificates.crt and it works. 
I will test the solution with the configmap later because it makes me simpler and cleaner than recreating a docker image.

The use of `REQUESTS_CA_BUNDLE` should be documented for those who cannot use `allow_insecure_registry`

You can close.

thanks

**Comment by cccs-rs** [comment]
Instructions for mounting internal root CAs can now be found in the Troubleshooting section of our docs:
https://cybercentrecanada.github.io/assemblyline4_docs/administration/troubleshooting/
