### ISSUE TITLE
Timeouts aren't being respected

### ISSUE THREAD

**Issue by jamie-34254** [CybercentreCanada/assemblyline-core#474]
As requested on Discord opening an issue here too.

I ran into the following two issues
https://github.com/CybercentreCanada/assemblyline-service-deobfuscripter/issues/21 and https://github.com/CybercentreCanada/assemblyline-service-vipermonkey/issues/32 which leads me to believe that the service timeout is not working.

@cccs-rs suggested this could be down to HPAs scaling the dispatcher here: https://discord.com/channels/908084610158714900/908717528082173983/942759109403496458 but I don't have any useful information to help with that theory apart from that we are using the HPA. 

I sometimes see services fail to timeout in groups all around the same time, I pulled up the HPA metrics:
<img width="1685" alt="image" src="https://user-images.githubusercontent.com/1857320/153866480-c3c1a611-ab57-4710-ac62-691e23b442d3.png">

One of the services failed to timeout around 2022-02-13 10:32:51,459 so I guess that is close enough to be related.

**Comment by jamie-34254** [comment]
Just to update on this - after turning off the HPA this issue becomes non existent, so I think that theory is likely to be correct.

**Comment by cccs-rs** [comment]
@jamie-34254 I believe [this PR](https://github.com/CybercentreCanada/assemblyline-core/pull/508) may have resolved the issue, can you verify?

4.2.0.stable68

**Comment by cccs-rs** [comment]
Will close issue for now. Re-open issue if this problem re-occurs.
