### ISSUE TITLE
Invalid score after fresh install

### ISSUE THREAD

**Issue by fabriow** [CybercentreCanada/assemblyline-core#573]
Hi,

It looks like there is a bug on a fresh install when score is computed for an analysis.
After services registration, all heuristics are successfully loaded into the datastore. But the service server is not reloaded (or maybe I missed something) and this part of code is not re-executed (as it is only executed in the object constructor):
https://github.com/CybercentreCanada/assemblyline-core/blob/63bbb17ca90d227747bca9ebb726bf605c6a498b/assemblyline_core/tasking_client.py#L53
I have to restart the service server and all heuristics with appropriate scores are successfully applied to the analysis.

Maybe a solution is to reload the heuristics from the datastore after a new service registration.

I can make a PR, but I think you known better than me the best way to solve this issue.

**Comment by cccs-douglass** [comment]
This should be resolved as of [build v4.2.0.stable118](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.2.0.stable118)
