### ISSUE TITLE
Updater fails to use HTTP_PROXY

### ISSUE THREAD

**Issue by eljeffeg** [CybercentreCanada/assemblyline-core#614]
Further review of the Updater may be required, but error logs show the request for docker hub tags doesn't use the http_proxy and thus fails to connect.

https://github.com/CybercentreCanada/assemblyline-core/blob/09db3f4e938d0f2856f23eb9b1a85c7e6b3337a4/assemblyline_core/updater/helper.py#L184

**Comment by cccs-rs** [comment]
Does the whole system have to go through your proxy to reach external addresses or is it just for reaching DockerHub?
You can set `HTTP_PROXY` and `HTTPS_PROXY` as the coreEnv for all core containers if that were the case.

If it's just the container registry then we can make a change regarding the configuration for custom registries in general and/or for reaching the public DockerHub

**Comment by eljeffeg** [comment]
I believe the whole system needs to go through the proxy to reach external addresses (I don't have full knowledge of the environment, but I've asked the admin to view this issue).  I just noticed the Updater was having issues and traced it back to that particular get request.  Hopefully this will help understand what has been done thus far and he can comment further if needed.

/etc/environment (for everything except apt)
```
http_proxy="http://proxy.example.com:80"
https_proxy="http://proxy.example.com:80"
ftp_proxy="http://proxy.example.com:80"
no_proxy="localhost,127.0.0.1,.example.com"
HTTP_PROXY="http://proxy.example.com:80"
HTTPS_PROXY="http://proxy.example.com:80"
FTP_PROXY="http://proxy.example.com:80"
NO_PROXY="localhost,127.0.0.1,.example.com"
```

/etc/apt/apt.conf.d/90curtin-aptproxy (for apt update/install)
```
Acquire::http::Proxy "http://proxy.example.com:80";
Acquire::https::Proxy "http://proxy.example.com:80";
```
/etc/systemd/system/docker.service.d/proxy.conf (for pulling docker images)
```
[Service]
Environment="HTTP_PROXY=http://proxy.example.com:80"
Environment="HTTPS_PROXY=https://proxy.example.com:443"
Environment="NO_PROXY=localhost,127.0.0.1,example.com"
```

We tried to add this to the ## ~/.docker/config.json file, but found this breaks the assemblyline container for some reason.
```
{
"proxies":
  {
   "default":
   {
     "httpProxy": "http://192.168.1.12:80",
     "httpsProxy": "http://192.168.1.12:80",
     "noProxy": "*.example.com,127.0.0.0/8"
   }
  }
}
```

**Comment by cccs-rs** [comment]
So in order to set the proxy environment variables for core, you'd have to modify your docker-compose and add the environment variable (and redeploy).

For services, there should be a configuration to add service-specific environment variables (`core.scaler.service_defaults.environment`):
https://cybercentrecanada.github.io/assemblyline4_docs/odm/models/config/#scalerservicedefaults
