### ISSUE TITLE
Redis overcomit memory

### ISSUE THREAD

**Issue by eljeffeg** [CybercentreCanada/assemblyline-core#682]
Noticed this error in my logs.. might be something to add.

redis_1           | 1:M 02 Feb 2023 15:06:09.237 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

**Comment by cccs-rs** [comment]
Since these errors seem to be coming from the Redis container, this isn't a core issue per se.

I would be interested to know if this is only present on the Docker appliance. If so, we could probably patch the command to run: `sysctl vm.overcommit_memory=1` before starting redis-server.

**Comment by cccs-rs** [comment]
Seems that since the container wouldn't have the appropriate privileges to set this from within, it must be set on the host:
https://github.com/docker-library/redis/issues/298#issuecomment-972275132

**Comment by cccs-rs** [comment]
Adding fix to Troubleshooting section in documentation as this is something that's to be performed by the user, not really something we can configure Assemblyline automatically on our side:
https://cybercentrecanada.github.io/assemblyline4_docs/administration/troubleshooting/
