### ISSUE TITLE
Category TagType

### ISSUE THREAD

**Issue by eljeffeg** [CybercentreCanada/assemblyline-core#692]
Working on AVClass, it has a few things it tries to identify with files.  It reports Behavior, Classification and Family.

- Behavior: Encrypts Files
- Classification: Ransomware
- Family: REvil

But I don't find a good TagType for Classification.  And while AVClass uses the term Classification, AssemblyLine uses that term to refer to things like TLP.  To avoid confusion, perhaps Category, Group or Type would be a better identifier for AL?  I think this might fit better as `file` behavior than `attribution`.

**Comment by cccs-sgaron** [comment]
We will add an attribution.category tag to fit this requirement.

**Comment by cccs-sgaron** [comment]
Here's the PR for it: https://github.com/CybercentreCanada/assemblyline-base/pull/1070
