### ISSUE TITLE
Error while trying to download extracted files

### ISSUE THREAD

**Issue by x1mus** [CybercentreCanada/assemblyline-core#79]
Here's how I'm having the bug.
I'm just creating a simple zip file, not protected by any passwords and submiting it to AL with the service "extract" checked.

The files in the archive are being extracted but when i click the button "Download File" after clicking on an extracted file an error occurs.

`{"api_error_message":"File 29cb482e07497a5b2d806df9a2b242440c189ed55086836762f4010f2cbaed69 is not associated to submission 4iLG6DPeArmCnmmLKvWpwK.","api_response":{},"api_server_version":"4.0.0","api_status_code":403}`

**Comment by cccs-douglass** [comment]
Can you tell us more? 
- Is on docker or kubernetes
- Are you using the default filestore settings
- is this happening for all extracted files, or only ones from extract with this context

**Comment by x1mus** [comment]
Hello !
It was on Docker, i didn't change any settings and I tried creating a simple service that basically just add a file with add_extracted(), the same problem happened

**Comment by x1mus** [comment]
With a totally new install, the problem does not seems to be there anymore.
